-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class * extends com.google.mlkit.common.model.** { *; }
-dontwarn com.google.mlkit.**
-dontwarn com.google.android.gms.**
